metadata/sdx_pull_1595230153817/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <inlineHelpText>Only Active client objectives are available as DTDs during sessions.</inlineHelpText>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/Client_Objective_TimeSeries__c.object-meta.xml
<CustomObject>
    <label>Client Objective TimeSeries</label>
    <nameField>
        <displayFormat>COTS-{YYYY}-{MM}-{0000000}</displayFormat>
        <label>COTS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objective TimeSeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Objectives_TS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client_Objective__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client-Objective</label>
    <referenceTo>Client_Objective__c</referenceTo>
    <relationshipLabel>Client Objective TimeSeries</relationshipLabel>
    <relationshipName>Client_Objective_TimeSeries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/RunId__c.field-meta.xml
<CustomField>
    <fullName>RunId__c</fullName>
    <label>RunId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/TS_Load_DateTime__c.field-meta.xml
<CustomField>
    <fullName>TS_Load_DateTime__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>TS Load DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestLFLDTDRates.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestLFLDTDRates
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test methods for LFLDTDRates
 *
 */

private class TestLFLDTDRates {
  /*******************************************************************************************************
   * @description Test getAcquisitionRate method
   * @param void
   *
   *
   * @example
   * TestLFLDTDRates.testGetAcquisitionRate();
   */

  @isTest
  static void testGetAcquisitionRate() {
    Test.startTest();
    LFLPopulateTestData.load();
    Id clientId = [SELECT id FROM Account WHERE FirstName = 'Test FName'].Id;
    List<Client_Objective_TimeSeries__c> tslist = new List<Client_Objective_TimeSeries__c>();
    Client_Objective_Timeseries__c tsrecord1 = new Client_Objective_Timeseries__c();
    tsrecord1.runId__c = 'AAAAA';
    //tsrecord.client_objective__c = co.Id;
    tsrecord1.client__c = clientId;
    tsrecord1.status__c = 'ACQ';
    tsrecord1.active__c = true;
    tslist.add(tsrecord1);

    Client_Objective_Timeseries__c tsrecord2 = new Client_Objective_Timeseries__c();
    tsrecord2.runId__c = 'BBB';
    //tsrecord.client_objective__c = co.Id;
    tsrecord2.client__c = clientId;
    tsrecord2.status__c = 'ACQ';
    tsrecord2.active__c = true;
    tslist.add(tsrecord2);

    Client_Objective_Timeseries__c tsrecord3 = new Client_Objective_Timeseries__c();
    tsrecord3.runId__c = 'BBB';
    //tsrecord.client_objective__c = co.Id;
    tsrecord3.client__c = clientId;
    tsrecord3.status__c = 'ACQ';
    tsrecord3.active__c = true;
    tslist.add(tsrecord3);

    insert tslist;
    String RecTypeId = [
      SELECT Id
      FROM RecordType
      WHERE Name = 'LFL Client' AND SobjectType = 'Account'
    ]
    .Id;

    Account newAccount1 = new Account(
      RecordTypeID = RecTypeId,
      FirstName = 'XX',
      LastName = 'YY',
      PersonHomePhone = '1234567',
      PersonMobilePhone = '12345678'
    );
    insert newAccount1;

    Test.stopTest();

    String s = LFLDTDRates.getAcquisitionRate(clientId, 0);
    String t = LFLDTDRates.getAcquisitionRate(newAccount1.Id, 0);

    System.assert((s != null) && (t != null));
  }

  /*******************************************************************************************************
   * @description Test  getAcquisitionRateByDates method
   * @param void
   *
   *
   * @example
   * TestLFLDTDRates.testGetAcquisitionRateByDates();
   */

  @isTest
  static void testGetAcquisitionRateByDates() {
    Test.startTest();
    LFLPopulateTestData.load();
    Id clientId = [SELECT id FROM Account WHERE FirstName = 'Test FName'].Id;
    List<Client_Objective_TimeSeries__c> tslist = new List<Client_Objective_TimeSeries__c>();
    Client_Objective_Timeseries__c tsrecord1 = new Client_Objective_Timeseries__c();
    tsrecord1.runId__c = 'AAAAA';
    //tsrecord.client_objective__c = co.Id;
    tsrecord1.client__c = clientId;
    tsrecord1.status__c = 'ACQ';
    tsrecord1.active__c = true;
    tslist.add(tsrecord1);

    Client_Objective_Timeseries__c tsrecord2 = new Client_Objective_Timeseries__c();
    tsrecord2.runId__c = 'BBB';
    //tsrecord.client_objective__c = co.Id;
    tsrecord2.client__c = clientId;
    tsrecord2.status__c = 'ACQ';
    tsrecord2.active__c = true;
    tslist.add(tsrecord2);

    Client_Objective_Timeseries__c tsrecord3 = new Client_Objective_Timeseries__c();
    tsrecord3.runId__c = 'BBB';
    //tsrecord.client_objective__c = co.Id;
    tsrecord3.client__c = clientId;
    tsrecord3.status__c = 'ACQ';
    tsrecord3.active__c = true;
    tslist.add(tsrecord3);

    insert tslist;
    String RecTypeId = [
      SELECT Id
      FROM RecordType
      WHERE Name = 'LFL Client' AND SobjectType = 'Account'
    ]
    .Id;

    Account newAccount1 = new Account(
      RecordTypeID = RecTypeId,
      FirstName = 'XX',
      LastName = 'YY',
      PersonHomePhone = '1234567',
      PersonMobilePhone = '12345678'
    );
    insert newAccount1;

    Test.stopTest();

    DateTime ed = DateTime.now();
    DateTime sd = ed.addMonths(-12);

    String s = LFLDTDRates.getAcquisitionRateByDates(clientId, sd, ed);
    String t = LFLDTDRates.getAcquisitionRateByDates(newAccount1.Id, sd, ed);

    System.assert((s != null) && (t != null));

    Boolean caughtTheDateError = false;
    try {
      String result = LFLDTDRates.getAcquisitionRateByDates(clientId, ed, sd);
    } catch (L4LRateCalculationException e) {
      caughtTheDateError = true;
      System.assert(caughtTheDateError == true);
    }
  }

  /*******************************************************************************************************
   * @description Test  testGetAcquisitionRateForClientTurbo method
   * @param void
   *
   *
   * @example
   * TestLFLDTDRates.testGetAcquisitionRateForClientTurbo();
   */

  @isTest
  static void testGetAcquisitionRateForClientTurbo() {
    Test.startTest();
    LFLPopulateTestData.load();
    Id clientId = [SELECT id FROM Account WHERE FirstName = 'Test FName'].Id;
    List<Client_Objective_TimeSeries__c> tslist = new List<Client_Objective_TimeSeries__c>();
    Client_Objective_Timeseries__c tsrecord1 = new Client_Objective_Timeseries__c();
    tsrecord1.runId__c = 'BBB';
    //tsrecord.client_objective__c = co.Id;
    tsrecord1.client__c = clientId;
    tsrecord1.status__c = 'ACQ';
    tsrecord1.active__c = true;
    tsrecord1.TS_Load_DateTime__c = DateTime.now().addDays(-7);
    tslist.add(tsrecord1);

    Client_Objective_Timeseries__c tsrecord2 = new Client_Objective_Timeseries__c();
    tsrecord2.runId__c = 'CCC';
    //tsrecord.client_objective__c = co.Id;
    tsrecord2.client__c = clientId;
    tsrecord2.status__c = 'ACQ';
    tsrecord2.active__c = true;
    tsrecord2.TS_Load_DateTime__c = DateTime.now().addDays(-14);

    tslist.add(tsrecord2);

    Client_Objective_Timeseries__c tsrecord3 = new Client_Objective_Timeseries__c();
    tsrecord3.runId__c = 'DDD';
    //tsrecord.client_objective__c = co.Id;
    tsrecord3.client__c = clientId;
    tsrecord3.status__c = 'ACQ';
    tsrecord3.active__c = true;
    tsrecord3.TS_Load_DateTime__c = DateTime.now().addDays(-14);
    tslist.add(tsrecord3);

    String RecTypeId = [
      SELECT Id
      FROM RecordType
      WHERE Name = 'LFL Client' AND SobjectType = 'Account'
    ]
    .Id;

    Account newAccount1 = new Account(
      RecordTypeID = RecTypeId,
      FirstName = 'XX',
      LastName = 'YY',
      PersonHomePhone = '1234567',
      PersonMobilePhone = '12345678'
    );
    insert newAccount1;

    Client_Objective_Timeseries__c tsrecord4 = new Client_Objective_Timeseries__c();
    tsrecord4.runId__c = 'AAAAA';
    //tsrecord.client_objective__c = co.Id;
    tsrecord4.client__c = newAccount1.Id;
    tsrecord4.status__c = 'ACQ';
    tsrecord4.active__c = true;
    tsrecord4.TS_Load_DateTime__c = DateTime.now().addDays(-100);

    tslist.add(tsrecord4);

    insert tslist;

    Test.stopTest();
    String s = LFLDTDRates.getAcquisitionRateforClientTurbo(clientId);
    // String t = LFLDTDRates.getAcquisitionRateforClientTurbo(newAccount1.Id);

    System.assert(s != null, 'expected a result');
  }
}