metadata/sdx_pull_1595230153817/unpackaged/objects/Account.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Account/fields/Current__c.field-meta.xml
<CustomField>
    <fullName>Current__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Client is currently receiving services from Abacus</description>
    <inlineHelpText>Client is currently receiving services from Abacus. A client has to be Current to generate fresh weekly statistics..</inlineHelpText>
    <label>Currently Receiving Abacus Services</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/First_Session__c.field-meta.xml
<CustomField>
    <fullName>First_Session__c</fullName>
    <label>First Closed Session</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DAOclasses/ClientDAO.cls
public with sharing class ClientDAO {
  public static final String RECORDTYPEID;

  static {
    RECORDTYPEID = [
      SELECT Id
      FROM RecordType
      WHERE Name = 'LFL Client' AND SobjectType = 'Account'
    ]
    .Id;
  }

  public ClientDAO() {
  }

  public static Account getClientById(Id clientId) {
    return [
      SELECT Id, FirstName, LastName, Current__c
      FROM Account
      WHERE Id = :clientId
      LIMIT 1
    ];
  }

  public static List<Account> getAllCurrentClients() {
    return [
      SELECT Id, FirstName, LastName, Current__c, First_Session__c
      FROM Account
      WHERE RecordTypeID = :RECORDTYPEID AND current__c = TRUE
    ];
  }
}