force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <inlineHelpText>Only Active client objectives are available as DTDs during sessions.</inlineHelpText>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client_Objective_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective_Notes__c</fullName>
    <label>Client_Objective_Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Absorbed__c.field-meta.xml
<CustomField>
    <fullName>Date_Absorbed__c</fullName>
    <label>Date Absorbed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Acquired__c.field-meta.xml
<CustomField>
    <fullName>Date_Acquired__c</fullName>
    <inlineHelpText>Date an objective is first acquired</inlineHelpText>
    <label>Date Acquired</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_CIP__c.field-meta.xml
<CustomField>
    <fullName>Date_CIP__c</fullName>
    <label>Date CIP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Held__c.field-meta.xml
<CustomField>
    <fullName>Date_Held__c</fullName>
    <label>Date Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Introduced__c.field-meta.xml
<CustomField>
    <fullName>Date_Introduced__c</fullName>
    <inlineHelpText>Date when status changed to OBJ</inlineHelpText>
    <label>Date Introduced</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Days_Since_Tested__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested__c</fullName>
    <formula>IF(NOT(ISNULL(Last_Tested__c)), today()-Last_Tested__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Tested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Days_Since_Tested_Correct__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested_Correct__c</fullName>
    <formula>IF(NOT(ISNULL(Last_Tested_Correct__c)), today()-Last_Tested_Correct__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Tested Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Re_Test_Recommended__c.field-meta.xml
<CustomField>
    <fullName>Re_Test_Recommended__c</fullName>
    <formula>AND(case(Frequency__c,
&quot;Twice-Weekly&quot;,if( Days_Since_Tested_Correct__c &gt;3,1,0),
&quot;Weekly&quot;,if( Days_Since_Tested_Correct__c &gt;7,1,0),
&quot;Fortnightly&quot;,if( Days_Since_Tested_Correct__c &gt;14,1,0),
&quot;Monthly&quot;,if( Days_Since_Tested_Correct__c &gt;30,1,0),
0)==1, ispickval(Status__c,&quot;ACQ&quot;),Active__c==true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Re-Test Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/Client_Objective_TimeSeries__c.object-meta.xml
<CustomObject>
    <label>Client Objective TimeSeries</label>
    <nameField>
        <displayFormat>COTS-{YYYY}-{MM}-{0000000}</displayFormat>
        <label>COTS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objective TimeSeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Objectives_TS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client_Objective__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client-Objective</label>
    <referenceTo>Client_Objective__c</referenceTo>
    <relationshipLabel>Client Objective TimeSeries</relationshipLabel>
    <relationshipName>Client_Objective_TimeSeries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client_Objective_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective_Notes__c</fullName>
    <label>Client_Objective_Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/CO_Name__c.field-meta.xml
<CustomField>
    <fullName>CO_Name__c</fullName>
    <label>CO Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Absorbed__c.field-meta.xml
<CustomField>
    <fullName>Date_Absorbed__c</fullName>
    <label>Date Absorbed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Acquired__c.field-meta.xml
<CustomField>
    <fullName>Date_Acquired__c</fullName>
    <inlineHelpText>Date an objective is first acquired</inlineHelpText>
    <label>Date Acquired</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_CIP__c.field-meta.xml
<CustomField>
    <fullName>Date_CIP__c</fullName>
    <label>Date CIP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Held__c.field-meta.xml
<CustomField>
    <fullName>Date_Held__c</fullName>
    <label>Date Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Introduced__c.field-meta.xml
<CustomField>
    <fullName>Date_Introduced__c</fullName>
    <inlineHelpText>Date when status changed to OBJ</inlineHelpText>
    <label>Date Introduced</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Days_Since_Tested__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested__c</fullName>
    <label>Days Since Tested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Days_Since_Tested_Correct__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested_Correct__c</fullName>
    <label>Days Since Tested Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Twice-Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipName>Client_Objectives_TS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Re_Test_Recommended__c.field-meta.xml
<CustomField>
    <fullName>Re_Test_Recommended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re. Test Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/RunId__c.field-meta.xml
<CustomField>
    <fullName>RunId__c</fullName>
    <label>RunId</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TimeSeries_Log__c/TimeSeries_Log__c.object-meta.xml
<CustomObject>
    <label>TimeSeries Log</label>
    <nameField>
        <displayFormat>TSL-{yyyy}-{mm}-{000000}</displayFormat>
        <label>TimeSeries Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TimeSeries Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TimeSeries_Log__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LFLTimeSeriesBatch.cls
public class LFLTimeSeriesBatch implements Database.Batchable<sObject>, Database.Stateful {
  public String query;
  public String email = 'mburnside@salesforce.com';
  public String runId;
  public integer recs = 0;

  public Database.querylocator start(Database.BatchableContext BC) {
    return Database.getQueryLocator(query);
  }
/**************************************************************
 * @name LFLTimeSeriesBatch
 * @author	Mike Burnside
 * @date	2023
 * @group Learning For Life
 *
 * @description	
 *
 */
 
  public void execute(Database.BatchableContext BC, List<sObject> scope) {
    List<Client_Objective_TimeSeries__c> tslist = new List<Client_Objective_TimeSeries__c>();

    for (sObject s : scope) {
      Client_Objective_TimeSeries__c tsrecord = new Client_Objective_TimeSeries__c();
      Client_Objective__c co = (Client_Objective__c) s;
      tsrecord.runId__c = runId;
      tsrecord.client_objective__c = co.Id;
      tsrecord.client__c = co.client__c;
      tsrecord.client_objective_notes__c = co.client_objective_notes__c;
      tsrecord.Date_Absorbed__c = co.Date_Absorbed__c;
      tsrecord.Date_Acquired__c = co.Date_Acquired__c;
      tsrecord.Date_CIP__c = co.Date_CIP__c;
      tsrecord.Date_Held__c = co.Date_Held__c;
      tsrecord.Date_Introduced__c = co.Date_Introduced__c;
      tsrecord.Days_Since_Tested_Correct__c = co.Days_Since_Tested_Correct__c;
      tsrecord.Days_Since_Tested__c = co.Days_Since_Tested__c;
      tsrecord.Frequency__c = co.Frequency__c;
      tsrecord.CO_Name__c = co.Name;
      tsrecord.Objective__c = co.Objective__c;
      tsrecord.Stage__c = co.Stage__c;
      tsrecord.Area__c = co.Area__c;
      tsrecord.status__c = co.status__c;
      tsrecord.active__c = co.active__c;
      tsrecord.Re_Test_Recommended__c = co.Re_Test_Recommended__c;

      tslist.add(tsrecord);
    }

    insert tslist;
    recs += tslist.size();
  }
  public void finish(Database.BatchableContext BC) {
    TimeSeries_Log__c endlog = new TimeSeries_Log__c();
    endlog.comments__c =
      'Successfully processed ' +
      recs +
      ' timeseries records';
    insert endlog;

    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

    mail.setToAddresses(new List<String>{ email });
    mail.setReplyTo('batch@acme.com');
    mail.setSenderDisplayName('Batch Processing');
    mail.setSubject('LFLTimeSeriesBatch completed.');

    mail.setPlainTextBody(
      'LFLTimeSeriesBatch completed successfully: ' +
        recs +
        ' Client Objective TimeSeries records created.'
    );

    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
  }
}