force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestTrgUniqueObjectivePerClientObjective.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestTrgUniqueObjectivePerClientObjective
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test trigger TrgUniqueObjectivePerClientObjective
 *
 */

private class TestTrgUniqueObjectivePerClientObjective {
  /*******************************************************************************************************
   * @description Test DuplicateObjectivePrevention
   * @param void
   *
   *
   * @example
   * TestTrgUniqueObjectivePerClientObjective.testDuplicateObjectivePrevention();
   */

  @isTest
  static void testDuplicateObjectivePrevention() {
    Test.startTest();
    LFLPopulateTestData.load();
    String RecTypeId = [
      SELECT Id
      FROM RecordType
      WHERE Name = 'LFL Client' AND SobjectType = 'Account'
    ]
    .Id;
    Account newAccount1 = new Account(
      RecordTypeID = RecTypeId,
      FirstName = 'XX',
      LastName = 'YY',
      PersonHomePhone = '1234567',
      PersonMobilePhone = '12345678'
    );
    insert newAccount1;

    Test.stopTest();

    Client_Objective__c co = [
      SELECT id, client__c, objective__c, status__c
      FROM client_objective__c
      LIMIT 1
    ];
    co.status__c = 'ACQ';

    Client_Objective__c co1 = new Client_Objective__c(
      client__c = newAccount1.Id,
      objective__c = co.objective__c,
      status__c = 'ACQ'
    );

    Client_Objective__c co2 = new Client_Objective__c(
      client__c = newAccount1.Id,
      objective__c = co.objective__c,
      status__c = 'CIP'
    );

    List<client_objective__c> lco = new List<client_objective__c>();
    lco.add(co);
    lco.add(co1);
    lco.add(co2);

    Boolean preventedDuplicate = false;
    try {
      insert lco; //insert a duplicate objective
    } catch (Exception e) {
      preventedDuplicate = true; //trigger detects duplicates objectives
    }
    System.assert(preventedDuplicate == true);
  }
}