force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/TestLFLInvocableListUnusedObj.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestLFLInvocableListUnusedObj
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test methods for LFLInvocableListUnusedObj
 *
 */

private class TestLFLInvocableListUnusedObj {
  /*******************************************************************************************************
   * @description Test LFLInvocableListUnusedObj
   * @param void
   *
   *
   * @example
   * TestL4LTimeSeries.test1();
   */

  @isTest
  static void test1() {
    Test.startTest();
    LFLPopulateTestData.load();
    List<Objective__c> objList = [SELECT id FROM objective__c];
    List<Client_Objective__c> clientobjList = [
      SELECT id, objective__c
      FROM client_objective__c
    ];
    Test.stopTest();

    List<L4LInvocableListUnusedObj.InputVariables> liv = new List<L4LInvocableListUnusedObj.InputVariables>();

    L4LInvocableListUnusedObj.InputVariables iv = new L4LInvocableListUnusedObj.InputVariables();
    iv.getClientObj = clientobjList;
    iv.getSDObj = objList;

    liv.add(iv);

    List<List<Objective__c>> res = L4LInvocableListUnusedObj.RemoveRecords(liv);

    System.assert(res[0].size() > 0);
  }
}