force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NDIS_Report__c/NDIS_Report__c.object-meta.xml
<CustomObject>
    <label>Report Wizard</label>
    <nameField>
        <displayFormat>REP-{00000}</displayFormat>
        <label>Report Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Report Wizards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NDIS_Report__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NDIS_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NDIS_Report__c/fields/NDIS_Report__c.field-meta.xml
<CustomField>
    <fullName>NDIS_Report__c</fullName>
    <label>Report Wizard</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvocableTest.cls
global with sharing class InvocableTest {
    
    @InvocableMethod(label='Mike Invocable method' description='Mikes invocable Method description')
    public static List<String> getStatusCountsBetweenDates (List<Requests> requests)   {
        
        // initialise our list of results
        
        List<String> result = new List<String>();
        
        String str='';
        
        DateTime starttime=requests[0].starttime;
        DateTime endtime=requests[0].endtime;
        Id clientId=requests[0].clientId;
      
        // execute a SOQL aggregate query
        AggregateResult[] groupedResults
            = [SELECT client__c, Objective__r.SD__r.Program__r.Name,status__c, count(id) 
               FROM Client_Objective__c 
               WHERE 
               client__c=:clientId and 
               status__c in ('ACQ','HLD','ABS','OBJ') and 
               lastmodifieddate > :starttime and lastmodifieddate <= :endtime  
               GROUP BY client__c,Objective__r.SD__r.Program__r.Name,status__c];
        
        System.debug(groupedResults);
        
        //hack to dedup progream names
        Set<String> programSet = new Set<String>();
        for (AggregateResult ar : groupedResults) {   
           programSet.add((String)ar.get('Name'));       
        }
        
        System.debug('No of programs='+programSet.size());
        
        if (programSet.size()>0){
        str+='<p>Total Number of Programs '+programSet.size()+ '</p>';
        // iterate through the aggregate set pulling out the fields we want and build our list -- default the "expr(0)"" refers to the first aggregation column
        }
        
        String oldpname='';
        
        for (AggregateResult ar : groupedResults)  {
            
            String statustext='';  
            String pname=(String)ar.get('Name');
            String status=(String)ar.get('Status__c');
            
            switch on status{
                when 'ACQ' {
                    statustext='Acquired';
                }
                when 'HLD'{
                    statustext='Held';
                    
                }
                when 'ABS'{
                    statustext='Absorbed';
                    
                }
                when 'OBJ'{
                    statustext='Current Objectives';
                    
                }
                when else {
                    statustext='????';
                }
            }
                       
            if (pname != oldpname) { // simulate a break report
                str+='<br/><p>Program: '+pname +'</p>'; 
            }
            str+='<p>Number '+statustext +' '+ar.get('expr0')+'</p>'; 
            
            oldpname=pname;
        }
        
        System.debug(str);
        
        // Flow now does the insert to the NDIS_Report__c object 
        //NDIS_Report__c ndr = new NDIS_Report__c();
        //ndr.client__c=clientId;
        //ndr.NDIS_Report__c=str;
        //insert ndr;
        
        result.add(str);
        return (result)  ; //return our list of results
    }
    
    global class Requests {
        
        @InvocableVariable
        global Id clientId;
        
        @InvocableVariable
        global DateTime starttime;
        
        @InvocableVariable
        global DateTime endtime;       
    }
    
    
}