force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <inlineHelpText>Only Active client objectives are available as DTDs during sessions.</inlineHelpText>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client_Objective_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective_Notes__c</fullName>
    <label>Client_Objective_Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Absorbed__c.field-meta.xml
<CustomField>
    <fullName>Date_Absorbed__c</fullName>
    <label>Date Absorbed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Acquired__c.field-meta.xml
<CustomField>
    <fullName>Date_Acquired__c</fullName>
    <inlineHelpText>Date an objective is first acquired</inlineHelpText>
    <label>Date Acquired</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_CIP__c.field-meta.xml
<CustomField>
    <fullName>Date_CIP__c</fullName>
    <label>Date CIP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Held__c.field-meta.xml
<CustomField>
    <fullName>Date_Held__c</fullName>
    <label>Date Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Date_Introduced__c.field-meta.xml
<CustomField>
    <fullName>Date_Introduced__c</fullName>
    <inlineHelpText>Date when status changed to OBJ</inlineHelpText>
    <label>Date Introduced</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Days_Since_Tested__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested__c</fullName>
    <formula>IF(NOT(ISNULL(Last_Tested__c)), today()-Last_Tested__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Tested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Days_Since_Tested_Correct__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested_Correct__c</fullName>
    <formula>IF(NOT(ISNULL(Last_Tested_Correct__c)), today()-Last_Tested_Correct__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Since Tested Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
                <default>true</default>
                <label>Weekly</label>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <formula>Objective__r.SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Re_Test_Recommended__c.field-meta.xml
<CustomField>
    <fullName>Re_Test_Recommended__c</fullName>
    <formula>AND(case(Frequency__c,
&quot;Twice-Weekly&quot;,if( Days_Since_Tested_Correct__c &gt;3,1,0),
&quot;Weekly&quot;,if( Days_Since_Tested_Correct__c &gt;7,1,0),
&quot;Fortnightly&quot;,if( Days_Since_Tested_Correct__c &gt;14,1,0),
&quot;Monthly&quot;,if( Days_Since_Tested_Correct__c &gt;30,1,0),
0)==1, ispickval(Status__c,&quot;ACQ&quot;),Active__c==true)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Re-Test Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/Client_Objective_TimeSeries__c.object-meta.xml
<CustomObject>
    <label>Client Objective TimeSeries</label>
    <nameField>
        <displayFormat>COTS-{YYYY}-{MM}-{0000000}</displayFormat>
        <label>COTS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objective TimeSeries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Client_Objectives_TS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client_Objective__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client-Objective</label>
    <referenceTo>Client_Objective__c</referenceTo>
    <relationshipLabel>Client Objective TimeSeries</relationshipLabel>
    <relationshipName>Client_Objective_TimeSeries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Client_Objective_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective_Notes__c</fullName>
    <label>Client_Objective_Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Absorbed__c.field-meta.xml
<CustomField>
    <fullName>Date_Absorbed__c</fullName>
    <label>Date Absorbed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Acquired__c.field-meta.xml
<CustomField>
    <fullName>Date_Acquired__c</fullName>
    <inlineHelpText>Date an objective is first acquired</inlineHelpText>
    <label>Date Acquired</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_CIP__c.field-meta.xml
<CustomField>
    <fullName>Date_CIP__c</fullName>
    <label>Date CIP</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Held__c.field-meta.xml
<CustomField>
    <fullName>Date_Held__c</fullName>
    <label>Date Held</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Date_Introduced__c.field-meta.xml
<CustomField>
    <fullName>Date_Introduced__c</fullName>
    <inlineHelpText>Date when status changed to OBJ</inlineHelpText>
    <label>Date Introduced</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Days_Since_Tested__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested__c</fullName>
    <label>Days Since Tested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Days_Since_Tested_Correct__c.field-meta.xml
<CustomField>
    <fullName>Days_Since_Tested_Correct__c</fullName>
    <label>Days Since Tested Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Twice-Weekly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipName>Client_Objectives_TS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <formula>Objective__r.SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Re_Test_Recommended__c.field-meta.xml
<CustomField>
    <fullName>Re_Test_Recommended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re. Test Recommended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective_TimeSeries__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLFLTimeSeriesBatch.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestLFLTimeSeriesBatch
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test methods for LFLTimeSeriesBatch
 *
 */

private class TestLFLTimeSeriesBatch {
  /*******************************************************************************************************
   * @description Test executeBatch
   * @param void
   *
   *
   * @example
   * TestLFLTimeSeriesBatch.testbatch();
   */

  @isTest
  static void testbatch() {
    Test.startTest();
    LFLPopulateTestData.load();
    Test.stopTest();

    LFLTimeSeriesBatch tsbatch = new LFLTimeSeriesBatch();

    tsbatch.query =
      'Select Id,Client__c,Client_Objective_Notes__c, Date_Absorbed__c,' +
      'Date_Acquired__c, Date_CIP__c, Date_Held__c, Date_Introduced__c,' +
      'Days_Since_Tested_Correct__c, Days_Since_Tested__c, Frequency__c,' +
      'Name, Objective__c, Program_Name__c, Area__c, Stage__c,' +
      'Re_Test_Recommended__c, Status__c, Active__c FROM Client_Objective__c limit 10';

    tsbatch.email = 'mburnside@salesforce.com';
    tsbatch.runId = 'test';

    ID batchprocessid = Database.executeBatch(tsbatch);

    String q = 'select count() from client_objective_timeseries__c';
    Integer i = database.countQuery(q);

    System.assert(i >= 0, 'integer result expected');
  }
}