force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <formula>Objective__r.SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/SD_Name__c.field-meta.xml
<CustomField>
    <fullName>SD_Name__c</fullName>
    <formula>Objective__r.SD_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SD Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/SDId__c.field-meta.xml
<CustomField>
    <fullName>SDId__c</fullName>
    <formula>CASESAFEID(Objective__r.SD__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Learning to Learn</fullName>
            </value>
            <value>
                <fullName>Imitation</fullName>
            </value>
            <value>
                <fullName>Play Skills</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Receptive Language</fullName>
            </value>
            <value>
                <fullName>Self-Care</fullName>
            </value>
            <value>
                <fullName>Matching</fullName>
            </value>
            <value>
                <fullName>Social Play Skills</fullName>
            </value>
            <value>
                <fullName>Speech</fullName>
            </value>
            <value>
                <fullName>Conversation</fullName>
            </value>
            <value>
                <fullName>Expressive Language</fullName>
            </value>
            <value>
                <fullName>Abstract Concepts</fullName>
            </value>
            <value>
                <fullName>Kinder Readiness</fullName>
            </value>
            <value>
                <fullName>School Readiness</fullName>
            </value>
            <value>
                <fullName>Language</fullName>
            </value>
            <value>
                <fullName>Expressive reasoning</fullName>
            </value>
            <value>
                <fullName>Community Access</fullName>
            </value>
            <value>
                <fullName>Abstract Language</fullName>
                <isActive>false</isActive>
                <label>Abstract Language</label>
            </value>
            <value>
                <fullName>Play-Skills</fullName>
                <isActive>false</isActive>
                <label>Play-Skills</label>
            </value>
            <value>
                <fullName>Receptive-Language</fullName>
                <isActive>false</isActive>
                <label>Receptive-Language</label>
            </value>
            <value>
                <fullName>SelfCare</fullName>
                <isActive>false</isActive>
                <label>SelfCare</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of the Stimulus</inlineHelpText>
    <label>SD Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/InUse__c.field-meta.xml
<CustomField>
    <fullName>InUse__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used by the SD Map Tile apex to indicate if any of the Objectives in the SD have been assigned to the Client</description>
    <label>InUse</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Match_Count__c.field-meta.xml
<CustomField>
    <fullName>Match_Count__c</fullName>
    <description>This field is used by the SD Map Tile apex to count the number of Objectives in the SD have been assigned to the Client</description>
    <label>Match Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Objective_Active_Count__c.field-meta.xml
<CustomField>
    <fullName>Objective_Active_Count__c</fullName>
    <label>Objective Active Count</label>
    <summaryFilterItems>
        <field>Objective__c.Status__c</field>
        <operation>equals</operation>
        <value>Active</value>
    </summaryFilterItems>
    <summaryForeignKey>Objective__c.SD__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <formula>Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/SDID__c.field-meta.xml
<CustomField>
    <fullName>SDID__c</fullName>
    <externalId>true</externalId>
    <label>SDID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SD__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage One</fullName>
            </value>
            <value>
                <fullName>Stage Two</fullName>
            </value>
            <value>
                <fullName>Stage Three</fullName>
            </value>
            <value>
                <fullName>Stage Four</fullName>
            </value>
            <value>
                <fullName>Stage Five</fullName>
            </value>
            <value>
                <fullName>Stage Six</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/L4LSDStageMap.cls
/**************************************************************
 * @author	Mike Burnside
 * @name L4LSDStageMap
 * @date	2023
 * @group Learning For Life
 *
 * @description
 *
 */

public with sharing class L4LSDStageMap {
  /*******************************************************************************************************
   * @description
   * @param clientId The Client ID
   *
   * @return A list of SDs
   *
   * @example
   */

  @AuraEnabled(cacheable=true)
  public static List<SD__c> removeDuplicates(String clientId) {
    // Query for a list of Client_Objective__c and SD__c objects
    List<Client_Objective__c> clientObjectives = [
      SELECT Id, SD_Name__c, Name, SDId__c
      FROM Client_Objective__c
      WHERE Client__c = :clientId
    ];
    List<SD__c> sdRecords = [
      SELECT
        Id,
        InUse__c,
        Name,
        Stage__c,
        Area__c,
        Program_Name__c,
        Objective_Active_Count__c,
        Description__c
      FROM SD__c
      ORDER BY Stage__c ASC NULLS LAST, Area__c
    ];

    // Create a map to store the unique SD__c records
    Map<Id, SD__c> uniqueSDRecords = new Map<Id, SD__c>();

    // Create a map to store the match count for each SD__c record
    Map<Id, Integer> sdMatchCount = new Map<Id, Integer>();

    // Iterate through the list of SD__c records
    for (SD__c sd : sdRecords) {
      // Set a flag to track whether the SD__c record has been matched to a Client_Objective__c record
      Boolean matchFound = false;

      // Iterate through the list of Client_Objective__c records
      for (Client_Objective__c co : clientObjectives) {
        // Check if the SDId__c field of the Client_Objective__c record matches the Id field of the SD__c record
        if (co.SDId__c == sd.Id) {
          // If a match is found, set the flag to true
          matchFound = true;

          // Increment the match count for the SD__c record
          if (sdMatchCount.containsKey(sd.Id)) {
            sdMatchCount.put(sd.Id, sdMatchCount.get(sd.Id) + 1);
          } else {
            sdMatchCount.put(sd.Id, 1);
          }
        }
      }

      // If the flag is still false (i.e. no match was found), add the SD__c record to the map
      if (!matchFound) {
        uniqueSDRecords.put(sd.Id, sd);
        sdMatchCount.put(sd.Id, 0);
      }

      // If the flag is true (i.e. match with ClientObj was found), update the InUse Flag and add the SD__c record to the map
      if (matchFound) {
        sd.InUse__c = true;
        uniqueSDRecords.put(sd.Id, sd);
      }
    }

    // Convert the map of unique SD__c records back into a list
    List<SD__c> uniqueSDList = new List<SD__c>(uniqueSDRecords.values());

    // Set the match count for each SD__c record in the list
    for (SD__c sd : uniqueSDList) {
      sd.Match_Count__c = sdMatchCount.get(sd.Id);
    }
    // Do something with the list of unique SD__c records
    System.debug(uniqueSDList);

    return uniqueSDList;
  }
}