force-app/main/default/objects/Client_Objective__c/Client_Objective__c.object-meta.xml
<CustomObject>
    <label>Client-Objective</label>
    <nameField>
        <displayFormat>CO-{000000}</displayFormat>
        <label>Client-Objective ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Client_Objective__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <inlineHelpText>Only Active client objectives are available as DTDs during sessions.</inlineHelpText>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Area__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Client_Objective_Notes__c.field-meta.xml
<CustomField>
    <fullName>Client_Objective_Notes__c</fullName>
    <label>Client_Objective_Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Client Objectives</relationshipLabel>
    <relationshipName>Client_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>Objective__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <formula>Objective__r.SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/SD_Name__c.field-meta.xml
<CustomField>
    <fullName>SD_Name__c</fullName>
    <formula>Objective__r.SD_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SD Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <formula>TEXT(Objective__r.SD__r.Stage__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client_Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OBJ</fullName>
            </value>
            <value>
                <fullName>ACQ</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
            <value>
                <fullName>ABS</fullName>
            </value>
            <value>
                <fullName>HLD</fullName>
            </value>
            <value>
                <fullName>1CP</fullName>
            </value>
            <value>
                <fullName>1IP</fullName>
            </value>
            <value>
                <fullName>DNC</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/SD_Name__c.field-meta.xml
<CustomField>
    <fullName>SD_Name__c</fullName>
    <formula>SD__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SD Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientObjectiveList.cls
public with sharing class ClientObjectiveList {
  @AuraEnabled(cacheable=true)
  public static List<Client_Objective__c> getClientObjectives(string clientId) {
    List<Client_Objective__c> tmpList = [
      SELECT
        Objective_Name__c,
        active__c,
        Objective__c,
        SD_Name__c,
        Program_Name__c,
        Status__c,
        Client_Objective_Notes__c,
        Stage__c,
        Area__c
      FROM Client_Objective__c
      LIMIT 10
    ];
    System.debug('xxxxx' + tmpList);

    return [
      SELECT
        active__c,
        Objective_Name__c,
        Objective__c,
        SD_Name__c,
        Program_Name__c,
        Status__c,
        Client_Objective_Notes__c,
        Stage__c,
        Area__c
      FROM Client_Objective__c
      WHERE Client__c = :clientId AND active__c = TRUE
      WITH SECURITY_ENFORCED
      ORDER BY Stage__c ASC NULLS LAST, Area__c
    ];
  }
}