force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <label>Correct</label>
    <inlineHelpText>The total number of Correct responses. Calculated by Stats Gatherer.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <label>Incorrect</label>
    <inlineHelpText>The total number of Incorrect responses. Calculated by Stats Gatherer.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <label>Prompted</label>
    <inlineHelpText>The total number of Prompted responses. Calculated by Stats Gatherer. </inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Obj__c/Session_Obj__c.object-meta.xml
<CustomObject>
    <label>Session-Obj</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Session-Obj ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Obj__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Correct</inlineHelpText>
    <label>C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Incorrect</inlineHelpText>
    <label>I</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/NonResponsive__c.field-meta.xml
<CustomField>
    <fullName>NonResponsive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>N</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Session Objectives</relationshipLabel>
    <relationshipName>Session_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>Objective__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <description>Used to capture the client&#39;s previous status on this objective at the time that the session is created.</description>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Prompted</inlineHelpText>
    <label>P</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Objectives</relationshipLabel>
    <relationshipName>Session_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/Session_Statistics__c.object-meta.xml
<CustomObject>
    <label>Session Statistics</label>
    <nameField>
        <displayFormat>SST-{000000}</displayFormat>
        <label>Session Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Statistics__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <label>Objective Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/TotalAcquiredCorrect__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredCorrect__c</fullName>
    <label>Total Acquired Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/TotalAcquiredPrompted__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredPrompted__c</fullName>
    <label>Total Acquired Prompted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LFLInvocableSessionStatistics.cls
/**************************************************************
 * @name LFLInvocableSessionStatistics
 * @author	Mike Burnside
 * @date	2023
 * @group Learning For Life
 *
 * @description Invocable methods, called from Flow to support session closure
 *
 */

public with sharing class LFLInvocableSessionStatistics {
  /*******************************************************************************************************
   * @name computeSessionStats
   * @description computes statistics for a session.
   * Inserts session_statistics__c records.
   * This method is an InvocableMethod and is called from Flow when a Session is closed.
   * Flow uses the returned String to update the session with a rich text summary.
   *
   *
   * @param sessions, a list of Ids
   * @return a list of responses List<Response> (i.e. a single String response to Flow)
   *
   * @example
   */

  @InvocableMethod
  public static List<Response> computeSessionStats(List<Id> sessions) {
    String SCENARIO = 'computeSessionStats() - invocable called from Flow - Apex';

    Logger.setScenario(SCENARIO);
    Logger.info('Apex:computeSessionStats() - invocable called from Flow')
      .setRecordId(sessions[0])
      .addTag('LFLInvocableSessionStatistics.computeSessionStats()')
      .addTag('logit()');

    Logger.saveLog();

    Id session = sessions[0];
    List<Response> responseList = new List<Response>();
    Response response = new Response();
    String PREVDEFAULT = 'BLANK';
    String previousStr;
    Integer totalCorrect = 0;
    Integer totalIncorrect = 0;
    Integer totalPrompted = 0;
    Integer totalNonResponsive = 0;

    Map<Id, Map<String, Integer>> correctMap = new Map<Id, Map<String, Integer>>();
    Map<Id, Map<String, Integer>> nonResponsiveMap = new Map<Id, Map<String, Integer>>();
    Map<Id, Map<String, Integer>> incorrectMap = new Map<Id, Map<String, Integer>>();
    Map<Id, Map<String, Integer>> promptedMap = new Map<Id, Map<String, Integer>>();

    Set<id> objectiveSet = new Set<Id>();
    Set<String> statusSet = new Set<String>();

    delete [SELECT id FROM Session_Statistics__c WHERE session__c = :session];

    for (Session_Obj__c so : [
      SELECT
        Objective__c,
        Objective_Name__c,
        Correct__c,
        NonResponsive__c,
        Incorrect__c,
        Prompted__c,
        previous_status__c,
        session__c
      FROM session_obj__c
      WHERE session__C = :session
    ]) {
      previousStr = (so.previous_status__c == null)
        ? PREVDEFAULT
        : so.previous_status__c;
      objectiveSet.add(so.objective__c);
      statusSet.add(previousStr);

      if (so.correct__c == true) {
        Map<String, Integer> corrStatus = new Map<String, Integer>();
        corrStatus = correctMap.get(so.objective__c);

        if (corrStatus != null) {
          if (corrStatus.get(previousStr) != null) {
            corrStatus.put(
              previousStr,
              (Integer) corrStatus.get(previousStr) + 1
            );
          } else {
            corrStatus.put(previousStr, 1);
          }
        } else {
          corrStatus = new Map<String, Integer>();
          corrStatus.put(previousStr, 1);
          correctMap.put(so.objective__c, corrStatus);
        }
      }
      if (so.nonresponsive__c == true) {
        Map<String, Integer> nonResponsiveStatus = new Map<String, Integer>();
        nonResponsiveStatus = nonResponsiveMap.get(so.objective__c);

        if (nonResponsiveStatus != null) {
          if (nonResponsiveStatus.get(previousStr) != null) {
            nonResponsiveStatus.put(
              previousStr,
              (Integer) nonResponsiveStatus.get(previousStr) + 1
            );
          } else {
            nonResponsiveStatus.put(previousStr, 1);
          }
        } else {
          nonResponsiveStatus = new Map<String, Integer>();
          nonResponsiveStatus.put(previousStr, 1);
          nonResponsiveMap.put(so.objective__c, nonResponsiveStatus);
        }
      }
      if (so.incorrect__c == true) {
        Map<String, Integer> incorrStatus = new Map<String, Integer>();
        incorrStatus = incorrectMap.get(so.objective__c);

        if (incorrStatus != null) {
          if (incorrStatus.get(previousStr) != null) {
            incorrStatus.put(
              previousStr,
              (Integer) incorrStatus.get(previousStr) + 1
            );
          } else {
            incorrStatus.put(previousStr, 1);
          }
        } else {
          incorrStatus = new Map<String, Integer>();
          incorrStatus.put(previousStr, 1);
          incorrectMap.put(so.objective__c, incorrStatus);
        }
      }
      if (so.prompted__c == true) {
        Map<String, Integer> promptedStatus = new Map<String, Integer>();
        promptedStatus = promptedMap.get(so.objective__c);

        if (promptedStatus != null) {
          if (promptedStatus.get(previousStr) != null) {
            promptedStatus.put(
              previousStr,
              (Integer) promptedStatus.get(previousStr) + 1
            );
          } else {
            promptedStatus.put(previousStr, 1);
          }
        } else {
          promptedStatus = new Map<String, Integer>();
          promptedStatus.put(previousStr, 1);
          promptedMap.put(so.objective__c, promptedStatus);
        }
      }
    }
    System.debug(correctMap);
    System.debug('correct ' + correctMap);
    System.debug('nonresponsive ' + nonResponsiveMap);
    System.debug('incorrect ' + incorrectMap);
    System.debug('prompted ' + promptedMap);

    // Logger.debug(
    //   'Apex:computeSessionStats() correctMap=' +
    //   correctMap +
    //   ' nonResponsiveMap=' +
    //   nonResponsiveMap +
    //   ' incorrectMap=' +
    //   incorrectMap +
    //   ' promptedMap=' +
    //   promptedMap
    // );

    Map<String, Integer> temp = new Map<String, Integer>();
    Integer count = 0;
    for (Id i : objectiveSet) {
      for (String s : statusSet) {
        count = 0;
        Boolean skip = true; // assume skip - this status wasn't present in this objective

        temp = correctMap.get(i);
        if (temp != null) {
          if (temp.keySet().contains(s))
            skip = false;
        }
        temp = nonResponsiveMap.get(i);
        if (temp != null) {
          if (temp.keySet().contains(s))
            skip = false;
        }
        temp = incorrectMap.get(i);
        if (temp != null) {
          if (temp.keySet().contains(s))
            skip = false;
        }
        temp = promptedMap.get(i);
        if (temp != null) {
          if (temp.keySet().contains(s))
            skip = false;
        }

        if (!skip) {
          /** Dont skip, there's a previous_status for this objective in correct, incorrect or prompted
         so create a statistics record
        **/
          Session_Statistics__c sessionStat = new Session_Statistics__c();
          sessionStat.session__c = session;
          sessionStat.objective__c = i;
          sessionStat.previous_status__c = s;

          temp = correctMap.get(i);
          if (temp != null) {
            count = (temp.get(s) != null) ? (Integer) temp.get(s) : 0;
            sessionStat.totalacquiredcorrect__c = count;
          } else
            sessionStat.totalacquiredcorrect__c = 0;
          totalCorrect += (Integer) sessionStat.totalacquiredcorrect__c;

          temp = nonResponsiveMap.get(i);
          if (temp != null) {
            count = (temp.get(s) != null) ? (Integer) temp.get(s) : 0;
            sessionStat.totalacquirednonresponsive__c = count;
          } else
            sessionStat.totalacquirednonresponsive__c = 0;
          totalNonResponsive += (Integer) sessionStat.totalacquirednonresponsive__c;

          temp = incorrectMap.get(i);
          if (temp != null) {
            count = (temp.get(s) != null) ? (Integer) temp.get(s) : 0;
            sessionStat.totalacquiredincorrect__c = count;
          } else
            sessionStat.totalacquiredincorrect__c = 0;
          totalIncorrect += (Integer) sessionStat.totalacquiredincorrect__c;

          temp = promptedMap.get(i);
          if (temp != null) {
            count = (temp.get(s) != null) ? (Integer) temp.get(s) : 0;
            sessionStat.totalacquiredprompted__c = count;
          } else
            sessionStat.totalacquiredprompted__c = 0;
          totalPrompted += (Integer) sessionStat.totalacquiredprompted__c;

          System.debug(sessionStat);
          insert sessionStat;

          Logger.debug(
              'Apex:computeSessionStats() inserted session_statistics__c'
            )
            .setRecordId(sessionStat.id)
            .addTag('LFLInvocableSessionStatistics.computeSessionStats()')
            .addTag('logit()');
          Logger.saveLog();
        }
      }
    }
    String current = System.now().format();
    Integer noOfObjectives = objectiveSet.size();
    Decimal percentage = ((totalCorrect +
      totalIncorrect +
      totalPrompted +
      totalNonResponsive) > 0)
      ? (Decimal) (totalCorrect *
        100 /
        (totalCorrect +
        totalNonResponsive +
        totalIncorrect +
        totalPrompted))
      : 0;

    response.outputString =
      '\n---------------------------------------------------------------' +
      '\nSuccessfully generated session statistics at ' +
      current +
      '\n---------------------------------------------------------------' +
      '\nDistinct Objectives: ' +
      noOfObjectives +
      '\nCorrect: ' +
      totalCorrect +
      '\nNonResponsive: ' +
      totalNonResponsive +
      '\nIncorrect: ' +
      totalIncorrect +
      '\nPrompted: ' +
      totalPrompted +
      '\n----------------------' +
      '\nPercent Correct: ' +
      percentage +
      '%' +
      '\n----------------------\n';
    responseList.add(response);
    return responseList;
  }

  public class Response {
    @InvocableVariable(
      label='Output'
      description='Calculate Statistics Result'
      required=true
    )
    public String outputString;
  }
}