force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLFLProgramStatusCascadeUtil.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestLFLProgramStatusCascadeUtil
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test methods for LFLProgramStatusCascadeUtil
 *
 */

private class TestLFLProgramStatusCascadeUtil {
  /*******************************************************************************************************
   * @description Test updateSDStatus method
   * @param void
   *
   *
   * @example
   * TestLFLProgramStatusCascadeUtil.testUpdateSDStatus();
   */

  @isTest
  static void testUpdateSDStatus() {
    Test.startTest();
    LFLPopulateTestData.load();
    Test.stopTest();

    Map<Id, String> statusMap = new Map<Id, String>();

    Program__c p = [
      SELECT id, status__c
      FROM Program__c
      WHERE status__c = 'Active'
      LIMIT 1
    ];
    statusMap.put(p.id, 'Inactive');

    LFLProgramStatusCascadeUtil.updateSDStatusByMap(statusMap);

    SD__c sd = [
      SELECT id, status__c
      FROM sd__c
      WHERE program__c = :p.id
      LIMIT 1
    ];

    System.assert(sd.status__c == 'Inactive', 'expected Inactive status');
  }

  /*******************************************************************************************************
   * @description Test updateObjectiveStatus method
   * @param void
   *
   *
   * @example
   * TestLFLProgramStatusCascadeUtil.testUpdateObjectiveStatus();
   */

  @isTest
  static void testUpdateObjectiveStatus() {
    Test.startTest();
    LFLPopulateTestData.load();
    Test.stopTest();

    Map<Id, String> statusMap = new Map<Id, String>();

    SD__c sd = [
      SELECT id, status__c
      FROM sd__c
      WHERE status__c = 'Active'
      LIMIT 1
    ];

    statusMap.put(sd.id, 'Inactive');

    LFLProgramStatusCascadeUtil.updateObjectiveStatusByMap(statusMap);

    objective__c o = [
      SELECT id, status__c
      FROM objective__c
      WHERE sd__c = :sd.id
      LIMIT 1
    ];

    System.assert(o.status__c == 'Inactive', 'comment goes here');
  }
}