force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <label>Correct</label>
    <inlineHelpText>The total number of Correct responses. Calculated by Stats Gatherer.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <label>Incorrect</label>
    <inlineHelpText>The total number of Incorrect responses. Calculated by Stats Gatherer.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <label>Prompted</label>
    <inlineHelpText>The total number of Prompted responses. Calculated by Stats Gatherer. </inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD_Name__c.field-meta.xml
<CustomField>
    <fullName>SD_Name__c</fullName>
    <formula>SD__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SD Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <inlineHelpText>The total number of Correct responses for Objectives associated with this Program. Calculated by Stats Gatherer.</inlineHelpText>
    <label>Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <inlineHelpText>The total number of Incorrect responses for Objectives associated with this Program. Calculated by Stats Gatherer.</inlineHelpText>
    <label>Incorrect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <inlineHelpText>The total number of Prompted responses for Objectives associated with this Program. Calculated by Stats Gatherer.</inlineHelpText>
    <label>Prompted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <inlineHelpText>The total number of Correct responses for Objectives associated with this SD. Calculated by Stats Gatherer</inlineHelpText>
    <label>Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <inlineHelpText>The total number of Incorrect responses for Objectives associated with this SD. Calculated by Stats Gatherer</inlineHelpText>
    <label>Incorrect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <label>Prompted
    </label>
    <inlineHelpText>The total number of Prompted responses. Calculated by Stats Gatherer.</inlineHelpText>

    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Obj__c/Session_Obj__c.object-meta.xml
<CustomObject>
    <label>Session-Obj</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Session-Obj ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Obj__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Correct</inlineHelpText>
    <label>C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Incorrect</inlineHelpText>
    <label>I</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Session Objectives</relationshipLabel>
    <relationshipName>Session_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>Objective__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>Objective__r.SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Prompted</inlineHelpText>
    <label>P</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <formula>Objective__r.SD__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Objectives</relationshipLabel>
    <relationshipName>Session_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MBSessionObjectives.cls
public with sharing class MBSessionObjectives {
   

    @AuraEnabled(cacheable=true) 
    public static List<Session_obj__c> getSessionObjectives (String sess) {
        
        return [SELECT Id,Name,Objective__c,Objective_Name__c,Correct__c,Incorrect__c,Prompted__c,SD__c FROM Session_Obj__c where Session__c = :sess];
    }


 @AuraEnabled(cacheable=true) 
    public static List<Objective__c> getObjectives (String sess) {
        
        return [SELECT Id,Name,Program__c,SD_Name__c FROM Objective__c order by Program__c,Name limit 20];
    }


 @AuraEnabled
    public static void deleteSessionObjectives (String sessionid) {
       delete [select id from Session_Obj__c where session__c=:sessionid];
      }

 @AuraEnabled
    public static void createSessionObjectives (String sessionid, String objective) {
        
Session_Obj__c so = new Session_Obj__c();
so.session__c=sessionid;
so.objective__c=objective;
so.Correct__C=false;
so.Incorrect__c=false;
so.Prompted__c=false;

insert so;


        
    }
@AuraEnabled 
    public static void setSessionObjectives(String key, String val) {
        
        Session_Obj__c so = [select id, Correct__c,Incorrect__c,Prompted__c from Session_Obj__c where id = :key limit 1];

switch on val {
   when 'Correct' {
      so.Correct__c=true;
      so.Incorrect__c=false;
      so.Prompted__c=false; 
   }
   when 'Incorrect' {
      so.Correct__c=false;
      so.Incorrect__c=true;
      so.Prompted__c=false; 
   }
    when 'Prompted' {
       so.Correct__c=false;
       so.Incorrect__c=false;
       so.Prompted__c=true; 
   }
   when else {
       System.debug('default');
   }
}

update so;

      
    }



@AuraEnabled 
    public static Integer setSessionObjectivesByArray(String jsonstr, String val) {
        
 List<Session_Obj__c> soDeserialized = (List<Session_Obj__c>) JSON.deserializeStrict(jsonstr, List<Session_Obj__c>.class);
 
 for(Session_Obj__c so : soDeserialized){

   switch on val {
   when 'Correct' {
      so.Correct__c=true;
      so.Incorrect__c=false;
      so.Prompted__c=false; 
   }
   when 'Incorrect' {
      so.Correct__c=false;
      so.Incorrect__c=true;
      so.Prompted__c=false; 
   }
    when 'Prompted' {
       so.Correct__c=false;
       so.Incorrect__c=false;
       so.Prompted__c=true; 
   }
   when else {
       System.debug('default');
   }
}

update soDeserialized;


      
 }


return soDeserialized.size();



}

}