force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/OID__c.field-meta.xml
<CustomField>
    <fullName>OID__c</fullName>
    <externalId>true</externalId>
    <label>OID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SDID__c.field-meta.xml
<CustomField>
    <fullName>SDID__c</fullName>
    <formula>SD__r.SDID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/PID__c.field-meta.xml
<CustomField>
    <fullName>PID__c</fullName>
    <externalId>true</externalId>
    <label>PID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage One</fullName>
            </value>
            <value>
                <fullName>Stage Two</fullName>
            </value>
            <value>
                <fullName>Stage Three</fullName>
            </value>
            <value>
                <fullName>Stage Four</fullName>
            </value>
            <value>
                <fullName>School Skills</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Learning to Learn</fullName>
            </value>
            <value>
                <fullName>Imitation</fullName>
            </value>
            <value>
                <fullName>Play Skills</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Receptive Language</fullName>
            </value>
            <value>
                <fullName>Self-Care</fullName>
            </value>
            <value>
                <fullName>Matching</fullName>
            </value>
            <value>
                <fullName>Social Play Skills</fullName>
            </value>
            <value>
                <fullName>Speech</fullName>
            </value>
            <value>
                <fullName>Conversation</fullName>
            </value>
            <value>
                <fullName>Expressive Language</fullName>
            </value>
            <value>
                <fullName>Abstract Concepts</fullName>
            </value>
            <value>
                <fullName>Kinder Readiness</fullName>
            </value>
            <value>
                <fullName>School Readiness</fullName>
            </value>
            <value>
                <fullName>Language</fullName>
            </value>
            <value>
                <fullName>Expressive reasoning</fullName>
            </value>
            <value>
                <fullName>Community Access</fullName>
            </value>
            <value>
                <fullName>Abstract Language</fullName>
                <isActive>false</isActive>
                <label>Abstract Language</label>
            </value>
            <value>
                <fullName>Play-Skills</fullName>
                <isActive>false</isActive>
                <label>Play-Skills</label>
            </value>
            <value>
                <fullName>Receptive-Language</fullName>
                <isActive>false</isActive>
                <label>Receptive-Language</label>
            </value>
            <value>
                <fullName>SelfCare</fullName>
                <isActive>false</isActive>
                <label>SelfCare</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/fields/PID__c.field-meta.xml
<CustomField>
    <fullName>PID__c</fullName>
    <formula>Program__r.PID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/SDID__c.field-meta.xml
<CustomField>
    <fullName>SDID__c</fullName>
    <externalId>true</externalId>
    <label>SDID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SD__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Stage One</fullName>
            </value>
            <value>
                <fullName>Stage Two</fullName>
            </value>
            <value>
                <fullName>Stage Three</fullName>
            </value>
            <value>
                <fullName>Stage Four</fullName>
            </value>
            <value>
                <fullName>Stage Five</fullName>
            </value>
            <value>
                <fullName>Stage Six</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LFLPostCopySandbox.cls
global class LFLPostCopySandbox implements SandboxPostCopy {
  global void runApexClass(SandboxContext context) {
    System.debug('Org ID: ' + context.organizationId());
    System.debug('Sandbox ID: ' + context.sandboxId());
    System.debug('Sandbox Name: ' + context.sandboxName());

    //Programs
    StaticResource sr = [
      SELECT Id, Body
      FROM StaticResource
      WHERE Name = 'programs'
      LIMIT 1
    ];
    String body = sr.Body.toString();
    String[] filelines = body.split('\n');
    String n = 'Program__c';

    List<Program__c> programs = new List<Program__c>();
    for (Integer i = 1; i < filelines.size(); i++) {
      String[] inputvalues = new List<String>{};
      inputvalues = filelines[i].split(',');
      Program__c p = new Program__c();
      if (inputvalues[1] == '')
        continue;
      p.PID__c = inputvalues[1];
      p.Name = inputvalues[0];
      p.stage__c = inputvalues[2];
      p.status__c = inputvalues[3];
      programs.add(p);
    }
    System.debug(programs.size() + ' Programs submitted for Upsert');
    upsert programs PID__c;

    // build a map of PIDs
    Map<String, Id> pidmap = new Map<String, Id>();
    for (Program__c pr : [SELECT PID__c, Id FROM program__c]) {
      pidmap.put(pr.PID__c, pr.Id);
    }

    //SDS
    sr = [
      SELECT Id, Body
      FROM StaticResource
      WHERE Name = 'sds'
      LIMIT 1
    ];
    System.debug(sr);
    body = sr.Body.toString();
    filelines = body.split('\n');
    n = 'SD__c';
    List<SD__c> sds = new List<SD__c>();

    for (Integer i = 1; i < filelines.size(); i++) {
      String[] inputvalues = new List<String>{};
      inputvalues = filelines[i].split(',');
      //System.debug(inputvalues);
      SD__c sd = new SD__c();

      String pid = inputvalues[5];

      sd.Program__c = (Id) pidmap.get(pid);
      sd.Name = inputvalues[0];
      sd.SDID__c = inputvalues[4];
      sd.stage__c = inputvalues[1];
      sd.status__c = inputvalues[2];
      sd.area__c = inputvalues[3];
      sds.add(sd);
    }
    upsert sds SDID__c;
    System.debug(sds.size() + ' SDs submitted for Upsert');

    // build a map of SDs
    Map<String, Id> sidmap = new Map<String, Id>();
    for (SD__c sd : [SELECT SDID__c, Id FROM sd__c]) {
      sidmap.put(sd.SDID__c, sd.Id);
    }

    sr = [
      SELECT Id, Body
      FROM StaticResource
      WHERE Name = 'objectives'
      LIMIT 1
    ];
    body = sr.Body.toString();
    filelines = body.split('\n');
    n = 'Objective__c';
    List<Objective__c> objs = new List<Objective__c>();

    for (Integer i = 1; i < filelines.size(); i++) {
      String[] inputvalues = new List<String>{};
      inputvalues = filelines[i].split(',');
      Objective__c o = new Objective__c();
      if (inputvalues[1] == '')
        continue;
      String sdid = inputvalues[3];

      o.sd__c = (Id) sidmap.get(sdid);
      o.Name = inputvalues[0];
      o.OID__c = inputvalues[1];
      o.status__c = inputvalues[2];

      objs.add(o);
    }
    upsert objs OID__c;
    System.debug(objs.size() + ' Objectives submitted for Upsert');

    // Insert logic here to prepare the sandbox for use.
  }
}