force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LFLProgramStatusCascadeUtil.cls
/**************************************************************
 * @name LFLProgramStatusCascadeUtil
 * @author	Mike Burnside
 * @date	2023
 * @group Learning For Life
 * @description Util class.
 * Methods for pushing of Status values down the hierarchy of Programs--< SD--< Objectives.
 * Status values are Active|Inactive|Draft
 */

public class LFLProgramStatusCascadeUtil {
  /*******************************************************************************************************
   * @name updateSDStatusByMap
   * @description Push changed Program status values to related SDs.
   * Invoked by Program__c trigger: trgCascadeProgramStatus.
   * @return void
   * @param statusMap Map of changed Program status values
   * @example
   */

  public static void updateSDStatusByMap(Map<id, string> statusMap) {
    Logger.debug('Apex:LFLProgramStatusCascadeUtil')
      .addTag('LFLProgramStatusCascadeUtil.updateSDStatusByMap()')
      .addTag('logit()');

    Logger.fine('statusMap=' + statusMap).addTag('logit()');
    Logger.saveLog();

    List<sd__c> sdlist = new List<sd__c>();
    List<sd__c> sdupdatelist = new List<sd__c>();

    sdlist = [
      SELECT id, status__c, program__c
      FROM sd__C
      WHERE program__c IN :statusMap.keySet()
    ];

    Logger.fine('Apex:LFLProgramStatusCascadeUtil sdlist=' + sdlist)
      .addTag('logit()');
    Logger.saveLog();

    for (sd__c sd : sdlist) {
      String status = statusMap.get(sd.program__c);
      sd.status__c = status;
      sdupdatelist.add(sd);
    }
    update sdupdatelist;
  }

  /*******************************************************************************************************
   * @name updateObjectiveStatusByMap
   * @description Push changed SD status values to related Objectives
   * Invoked by SD__c trigger: trgCascadeSDStatus
   * @param statusMap Map of changed SD status values
   * @return void
   * @example
   */

  public static void updateObjectiveStatusByMap(Map<id, string> statusMap) {
    Logger.debug('Apex:LFLProgramStatusCascadeUtil')
      .addTag('LFLProgramStatusCascadeUtil.updateObjectiveStatusByMap()')
      .addTag('logit()');

    Logger.fine('statusMap=' + statusMap).addTag('logit()');
    Logger.saveLog();

    List<objective__c> olist = new List<objective__c>();
    List<objective__c> oupdatelist = new List<objective__c>();

    olist = [
      SELECT id, status__c, sd__c
      FROM objective__C
      WHERE sd__c IN :statusMap.keySet()
    ];
    Logger.fine('Apex:LFLProgramStatusCascadeUtil olist=' + olist)
      .addTag('logit()');
    Logger.saveLog();

    for (objective__c o : olist) {
      String status = statusMap.get(o.sd__c);
      o.status__c = status;
      oupdatelist.add(o);
    }
    update oupdatelist;
  }
}