force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today ()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/Session_Statistics__c.object-meta.xml
<CustomObject>
    <label>Session Statistics</label>
    <nameField>
        <displayFormat>SST-{000000}</displayFormat>
        <label>Session Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Statistics__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/TotalAcquiredCorrect__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredCorrect__c</fullName>
    <label>Total Acquired Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/TotalAcquiredPrompted__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredPrompted__c</fullName>
    <label>Total Acquired Prompted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LFLAggregateResultIterable5.cls
public class LFLAggregateResultIterable5 implements Iterable<AggregateResult> {
  public Iterator<AggregateResult> iterator() {
    List<AggregateResult> aggresults = [
      SELECT
        objective__r.sd__r.program__c,
        objective__r.sd__r.program__r.Name progname,
        count(id) ssrecords,
        count_distinct(session__c) sessions,
        count_distinct(session__r.client__c) clients,
        sum(TotalAcquiredCorrect__c) correct,
        sum(TotalAcquiredInCorrect__c) incorrect,
        sum(TotalAcquirednonREsponsive__c) noresponsive,
        Sum(TotalAcquiredprompted__c) prompted,
        Min(Session__r.Date__c) earliest_session_date,
        Max(Session__r.Date__c) latest_session_date
      FROM session_Statistics__c
      WHERE objective__c != NULL AND lastmodifieddate = LAST_N_DAYS:500
      GROUP BY objective__r.sd__r.program__c, objective__r.sd__r.program__r.Name
    ];
    return new LFLAggregateResultIterator(aggresults);
  }
}