force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LFLPostCopySandboxTest.cls
@isTest
class LFLPostCopySandboxTest {
  @isTest
  static void myUnitTest() {
    Test.startTest();
    Test.testSandboxPostCopyScript(
      new LFLPostCopySandbox(),
      UserInfo.getOrganizationId(),
      UserInfo.getOrganizationId(),
      UserInfo.getOrganizationName()
    );

    Test.stopTest();
    Integer pcount = [SELECT COUNT() FROM Program__c];
    Integer scount = [SELECT COUNT() FROM SD__c];
    Integer ocount = [SELECT COUNT() FROM Objective__c];

    System.assert(pcount > 5, 'expected 5+');
    System.assert(scount > 500, 'expected 500+');
    System.assert(ocount > 5000, 'expected 5000+');
  }
}