force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today ()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/Session_Statistics__c.object-meta.xml
<CustomObject>
    <label>Session Statistics</label>
    <nameField>
        <displayFormat>SST-{000000}</displayFormat>
        <label>Session Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Statistics__c/fields/icon__c.field-meta.xml
<CustomField>
    <fullName>icon__c</fullName>
    <formula>IF( 
Percent_Correct__c &lt;  $CustomMetadata.LFL_Stats_Boundary__mdt.lfl_stats_boundary.Low__c, 
IMAGE(&quot;/resource/red&quot;, &quot;red&quot;),
IF( Percent_Correct__c &gt;= $CustomMetadata.LFL_Stats_Boundary__mdt.lfl_stats_boundary.High__c,
IMAGE(&quot;/resource/green&quot;, &quot;green&quot;),
IMAGE(&quot;/resource/orange&quot;, &quot;orange&quot;)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/iconstr__c.field-meta.xml
<CustomField>
    <fullName>iconstr__c</fullName>
    <formula>IF(
Percent_Correct__c &lt;  $CustomMetadata.LFL_Stats_Boundary__mdt.lfl_stats_boundary.Low__c,
&quot;/resource/red&quot;,
IF( Percent_Correct__c &gt;=  $CustomMetadata.LFL_Stats_Boundary__mdt.lfl_stats_boundary.High__c,
&quot;/resource/green&quot;,
&quot;/resource/orange&quot;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>iconstr</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Percent_Correct__c.field-meta.xml
<CustomField>
    <fullName>Percent_Correct__c</fullName>
    <formula>TotalAcquiredCorrect__c / ( TotalAcquiredCorrect__c + TotalAcquiredIncorrect__c + TotalAcquiredPrompted__c +  TotalAcquiredNonResponsive__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percent Correct</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/TotalAcquiredCorrect__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredCorrect__c</fullName>
    <label>Total Acquired Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session_Statistics__c/fields/TotalAcquiredPrompted__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredPrompted__c</fullName>
    <label>Total Acquired Prompted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/L4LSessionStatsController.cls
public with sharing class L4LSessionStatsController {
  @AuraEnabled(cacheable=true)
  public static List<Session_Statistics__c> getSessionStats(String searchKey) {
    Logger.setScenario('L4LSessionStatsController');
    Logger.debug('Apex:getSessionStats() recordId=' + searchKey)
      .setRecordId(searchKey)
      .addTag('L4LController.getSessionStats()')
      .addTag('logit()');

    List<Session_Statistics__c> results = new List<Session_Statistics__c>(
      [
        SELECT
          id,
          name,
          objective__r.name,
          session__r.name,
          previous_status__c,
          icon__c,
          iconstr__c,
          totalacquiredcorrect__c,
          totalacquiredincorrect__c,
          totalacquiredprompted__c,
          Percent_Correct__c,
          Program_Name__c
        FROM session_statistics__c
        WHERE session__c = :searchKey
        ORDER BY program_name__c
      ]
    );

    Logger.debug('Apex:getSessionStats() results=' + results)
      .setRecordId(searchKey)
      .addTag('L4LController.getSessionStats()')
      .addTag('logit()');
    Logger.saveLog();

    return results;
  }
  @AuraEnabled(cacheable=true)
  public static List<Session_Statistics__c> getD3Stats(
    String clientId,
    Boolean showAcquired
  ) {
    Logger.setScenario('L4LSessionStatsController');
    Logger.debug(
        'Apex:getD3Stats() recordId=' +
        clientId +
        ' showAcquired=' +
        showAcquired
      )
      .setRecordId(clientId)
      .addTag('L4LController.getD3Stats()')
      .addTag('logit()');

    // List<Session_Statistics__c> results = new List<Session_Statistics__c>();
    // if (showAcquired) {
    //   results = [
    //     SELECT
    //       session__r.name,
    //       session__r.client__c,
    //       session__r.client__r.name,
    //       program_name__c,
    //       objective__r.name,
    //       session__r.Date__c,
    //       previous_status__c,
    //       Percent_Correct__c
    //     FROM Session_Statistics__c
    //     WHERE session__r.client__c = :clientId AND previous_status__c = 'ACQ'
    //   ];
    // } else {
    //   results = [
    //     SELECT
    //       session__r.name,
    //       session__r.client__c,
    //       session__r.client__r.name,
    //       program_name__c,
    //       objective__r.name,
    //       session__r.Date__c,
    //       previous_status__c,
    //       Percent_Correct__c
    //     FROM Session_Statistics__c
    //     WHERE session__r.client__c = :clientId
    //   ];
    // }

    // return results;

    String querySessionStatsString =
      'SELECT session__r.name, session__r.client__c, session__r.client__r.name, program_name__c, ' +
      'objective__r.name  ,session__r.Date__c ,previous_status__c ,Percent_Correct__c ' +
      'FROM Session_Statistics__c ' +
      'WHERE session__r.client__c = :clientId ';

    if (showAcquired)
      querySessionStatsString += ' AND previous_status__c = \'ACQ\' ';

    querySessionStatsString += 'ORDER BY session__r.name, objective__r.name ';

    Logger.debug(
        'Apex:getD3Stats() querySessionStatsStr=' + querySessionStatsString
      )
      .setRecordId(clientId)
      .addTag('L4LSessionStatsController.getD3Stats()')
      .addTag('logit()');
    Logger.saveLog();

    List<Session_Statistics__c> results = new List<Session_Statistics__c>();
    results = Database.query(querySessionStatsString);

    return results;
  }

  @AuraEnabled(cacheable=true)
  public static List<Session_Statistics__c> getD3StatsByProgram(
    String clientId,
    String programStr,
    Boolean showAcquired
  ) {
    Logger.setScenario('L4LSessionStatsController');
    Logger.debug(
        'Apex:getD3StatsByProgram() recordId=' +
        clientId +
        ' showAcquired=' +
        showAcquired
      )
      .setRecordId(clientId)
      .addTag('L4LController.getD3StatsByProgram()')
      .addTag('logit()');

    String querySessionStatsString =
      'SELECT session__r.name, session__r.client__c, session__r.client__r.name, program_name__c, ' +
      'objective__r.name  ,session__r.Date__c ,previous_status__c ,Percent_Correct__c ' +
      'FROM Session_Statistics__c ' +
      'WHERE session__r.client__c = :clientId AND program_name__c=:programStr ';

    if (showAcquired)
      querySessionStatsString += ' AND previous_status__c = \'ACQ\' ';

    querySessionStatsString += 'ORDER BY session__r.name, objective__r.name ';

    Logger.debug(
        'Apex:getD3Stats() querySessionStatsStr=' + querySessionStatsString
      )
      .setRecordId(clientId)
      .addTag('L4LSessionStatsController.getD3StatsByProgram()')
      .addTag('logit()');
    Logger.saveLog();

    List<Session_Statistics__c> results = new List<Session_Statistics__c>();
    results = Database.query(querySessionStatsString);
    return results;
  }
}