force-app/main/default/objects/Session_Statistics__c/Session_Statistics__c.object-meta.xml
<CustomObject>
    <label>Session Statistics</label>
    <nameField>
        <displayFormat>SST-{000000}</displayFormat>
        <label>Session Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Statistics__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <label>Program Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestLFLSessionStatsTrg.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestLFLSessionStatsTrg
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test methods for LFLSessionStatsTrg
 *
 */

private class TestLFLSessionStatsTrg {
  /*******************************************************************************************************
   * @description Test trigger
   * @param void
   *
   *
   * @example
   * TestLFLSessionStatsTrg.testTrg();
   */

  @isTest
  static void testTrg() {
    Test.startTest();
    //the test load contains a single session_objective where correct__c=false and previous_status='ACQ'
    LFLPopulateTestData.load();
    Test.stopTest();

    Session_Statistics__c ss = [
      SELECT id, program_name__c
      FROM session_statistics__c
      LIMIT 1
    ];

    System.assert(
      ss.program_name__c != null,
      'expected program name to be present'
    );
  }
}