force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Session_Location__c.field-meta.xml
<CustomField>
    <fullName>Session_Location__c</fullName>
    <label>Session Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LFL-Kew</fullName>
            </value>
            <value>
                <fullName>Client-Home</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Kinder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestLFLInvocableSessionStatistics.cls
@isTest
/**************************************************************
 * @author	Mike Burnside
 * @name TestLFLInvocableSessionStatistics
 * @date	2022
 * @group Learning For Life Testing
 *
 * @description	Test methods for LFLInvocableSessionStatistics
 *
 */

private class TestLFLInvocableSessionStatistics {
  /*******************************************************************************************************
   * @description Test computeSessionStats method
   * @param void
   *
   *
   * @example
   * TestLFLInvocableSessionStatistics.testComputeSessionStats();
   */

  @isTest
  static void testComputeSessionStats() {
    Test.startTest();
    LFLPopulateTestData.load();
    Test.stopTest();

    Id req = [
      SELECT id
      FROM session__c
      WHERE session_location__c = 'Other'
      LIMIT 1
    ]
    .id;
    List<id> reqList = new List<Id>();
    reqList.add(req);

    List<LFLInvocableSessionStatistics.Response> result = LFLInvocableSessionStatistics.computeSessionStats(
      reqlist
    );
    System.assert(result[0].outputString.contains('Success'));
  }
}