force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Statistics__c/Session_Statistics__c.object-meta.xml
<CustomObject>
    <label>Session Statistics</label>
    <nameField>
        <displayFormat>SST-{000000}</displayFormat>
        <label>Session Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Statistics__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Statistics</relationshipLabel>
    <relationshipName>Session_Statistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestL4LSessionStatsController.cls
@isTest
private class TestL4LSessionStatsController {
  @isTest
  static void testGetsessionObjectives() {
    Test.startTest();
    LFLPopulateTestData.load();
    Id sessionId = [SELECT id FROM session__c LIMIT 1].Id;
    Test.stopTest();

    List<session_statistics__c> so = L4LSessionStatsController.getSessionStats(
      sessionId
    );
    System.assert(
      so.size() > 0,
      'Expected at least one session_statistics__c record retrieved.'
    );
  }
  @isTest
  static void testGetD3Stats() {
    Test.startTest();
    LFLPopulateTestData.load();
    Id clientId = [SELECT id FROM Account WHERE FirstName = 'Test FName'].Id;
    Test.stopTest();

    List<session_statistics__c> so = L4LSessionStatsController.getD3Stats(
      clientId,
      true
    );
    System.assert(
      so.size() > 0,
      'Expected at least one session_statistics__c record retrieved.'
    );
    so = L4LSessionStatsController.getD3Stats(clientId, false);
    System.assert(
      so.size() > 0,
      'Expected at least one session_statistics__c record retrieved.'
    );
  }

  @isTest
  static void testGetD3StatsByProgram() {
    Test.startTest();
    LFLPopulateTestData.load();
    Id clientId = [SELECT id FROM Account WHERE FirstName = 'Test FName'].Id;
    Test.stopTest();

    List<session_statistics__c> so = L4LSessionStatsController.getD3StatsByProgram(
      clientId,
      'Color',
      true
    );
    System.assert(
      so.size() == 0,
      '??Expected at least one session_statistics__c record retrieved.'
    );
    so = L4LSessionStatsController.getD3StatsByProgram(
      clientId,
      'Color',
      false
    );
    System.assert(
      so.size() == 0,
      '??Expected at least one session_statistics__c record retrieved.'
    );
  }
}