force-app/main/default/objects/Mastery_Statistics__c/Mastery_Statistics__c.object-meta.xml
<CustomObject>
    <description>deprecated on 30/1/2023</description>
    <label>Mastery Statistics</label>
    <nameField>
        <displayFormat>MSST-{000000}</displayFormat>
        <label>Mastery Statistics Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mastery Statistics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Mastery_Statistics__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mastery Statistics</relationshipLabel>
    <relationshipName>Mastery_Statistics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mastery_Statistics__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <label>Previous Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mastery_Statistics__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Mastery Statistics</relationshipLabel>
    <relationshipName>Mastery_Statistics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mastery_Statistics__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Mastery Statistics</relationshipLabel>
    <relationshipName>Mastery_Statistics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Mastery_Statistics__c/fields/TotalAcquiredIncorrect__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredIncorrect__c</fullName>
    <label>Total Acquired Incorrect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mastery_Statistics__c/fields/TotalAcquiredNonResponsive__c.field-meta.xml
<CustomField>
    <fullName>TotalAcquiredNonResponsive__c</fullName>
    <label>TotalAcquiredNonResponsive</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <label>Correct</label>
    <inlineHelpText>The total number of Correct responses. Calculated by Stats Gatherer.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <label>Incorrect</label>
    <inlineHelpText>The total number of Incorrect responses. Calculated by Stats Gatherer.</inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <label>Prompted</label>
    <inlineHelpText>The total number of Prompted responses. Calculated by Stats Gatherer. </inlineHelpText>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Objective__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SD</label>
    <referenceTo>SD__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <inlineHelpText>The total number of Correct responses for Objectives associated with this Program. Calculated by Stats Gatherer.</inlineHelpText>
    <label>Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <inlineHelpText>The total number of Incorrect responses for Objectives associated with this Program. Calculated by Stats Gatherer.</inlineHelpText>
    <label>Incorrect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Program__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <inlineHelpText>The total number of Prompted responses for Objectives associated with this Program. Calculated by Stats Gatherer.</inlineHelpText>
    <label>Prompted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/SD__c.object-meta.xml
<CustomObject>
    <label>SD</label>
    <nameField>
        <label>SD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SD__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <inlineHelpText>The total number of Correct responses for Objectives associated with this SD. Calculated by Stats Gatherer</inlineHelpText>
    <label>Correct</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <inlineHelpText>The total number of Incorrect responses for Objectives associated with this SD. Calculated by Stats Gatherer</inlineHelpText>
    <label>Incorrect</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>SDs</relationshipLabel>
    <relationshipName>SDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SD__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <label>Prompted
    </label>
    <inlineHelpText>The total number of Prompted responses. Calculated by Stats Gatherer.</inlineHelpText>

    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Session Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/Session_Obj__c.object-meta.xml
<CustomObject>
    <label>Session-Obj</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Session-Obj ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Objectives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Obj__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Correct</inlineHelpText>
    <label>C</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Incorrect__c.field-meta.xml
<CustomField>
    <fullName>Incorrect__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Incorrect</inlineHelpText>
    <label>I</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/NonResponsive__c.field-meta.xml
<CustomField>
    <fullName>NonResponsive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>N</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Objective__c.field-meta.xml
<CustomField>
    <fullName>Objective__c</fullName>
    <label>Objective</label>
    <referenceTo>Objective__c</referenceTo>
    <relationshipLabel>Session Objectives</relationshipLabel>
    <relationshipName>Session_Objectives</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>Objective_Name__c</fullName>
    <formula>Objective__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Previous_Status__c.field-meta.xml
<CustomField>
    <fullName>Previous_Status__c</fullName>
    <description>Used to capture the client&#39;s previous status on this objective at the time that the session is created.</description>
    <label>Previous Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>CIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <formula>Objective__r.SD__r.Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Prompted__c.field-meta.xml
<CustomField>
    <fullName>Prompted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Prompted</inlineHelpText>
    <label>P</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/SD__c.field-meta.xml
<CustomField>
    <fullName>SD__c</fullName>
    <formula>Objective__r.SD__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SD</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Obj__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Objectives</relationshipLabel>
    <relationshipName>Session_Objectives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LFLInvocableMasteryStatistics.cls
/**************************************************************
 * @name LFLDTDRates
 * @author	Mike Burnside
 * @date	2023
 * @deprecated
 * @group Learning For Life - DEPRECATED
 * @description	Deprecated on 30/1/2023.
 * Roll up stats to the Program level.  
 *
 */

public with sharing class LFLInvocableMasteryStatistics {
  @InvocableMethod
  public static List<Response> computeMasteryStats(List<Id> sessions) {
    Logger.setScenario('LFLInvocableSessionStatistics');
    Logger.debug('Apex:computeMasteryStats() - invocable called from Flow')
      .setRecordId(sessions[0])
      .addTag('LFLInvocableSessionStatistics.computeMasteryStats()')
      .addTag('logit()');

    Id session = sessions[0];
    List<Response> responseList = new List<Response>();
    Response response = new Response();
    String PREVDEFAULT = 'BLANK';
    Id programId;
    Integer totalCorrect = 0;
    Integer totalIncorrect = 0;
    Integer totalPrompted = 0;
    Integer totalNonResponsive = 0;

    Id clientId;

    Map<Id, Integer> correctMap = new Map<Id, Integer>();
    Map<Id, Integer> nonResponsiveMap = new Map<Id, Integer>();
    Map<Id, Integer> incorrectMap = new Map<Id, Integer>();
    Map<Id, Integer> promptedMap = new Map<Id, Integer>();

    Set<Id> programSet = new Set<Id>();
    //Set<String> statusSet = new Set<String>();

    delete [SELECT id FROM Mastery_Statistics__c WHERE session__c = :session];

    for (Session_Obj__c so : [
      SELECT
        Objective__c,
        session__r.Client__c,
        Objective_Name__c,
        Correct__c,
        NonResponsive__c,
        Incorrect__c,
        Prompted__c,
        previous_status__c,
        session__c,
        objective__r.sd__r.program__c
      FROM session_obj__c
      WHERE session__C = :session AND previous_status__c = 'ACQ'
    ]) {
      programId = so.objective__r.sd__r.program__c;
      programSet.add(programId);
      clientId = so.session__r.Client__c;

      if (so.correct__c == true) {
        Integer i = (Integer) correctMap.get(programId);
        if (i != null) {
          correctMap.put(programId, i + 1);
        } else {
          correctMap.put(programId, 1);
        }
      }
      if (so.nonresponsive__c == true) {
        Integer i = (Integer) nonResponsiveMap.get(programId);
        if (i != null) {
          nonResponsiveMap.put(programId, i + 1);
        } else {
          nonResponsiveMap.put(programId, 1);
        }
      }

      if (so.incorrect__c == true) {
        Integer i = (Integer) incorrectMap.get(programId);
        if (i != null) {
          incorrectMap.put(programId, i + 1);
        } else {
          incorrectMap.put(programId, 1);
        }
      }
      if (so.prompted__c == true) {
        Integer i = (Integer) promptedMap.get(programId);
        if (i != null) {
          promptedMap.put(programId, i + 1);
        } else {
          promptedMap.put(programId, 1);
        }
      }
    }
    System.debug(correctMap);
    System.debug('correct ' + correctMap);
    System.debug('nonresponsive ' + nonResponsiveMap);
    System.debug('incorrect ' + incorrectMap);
    System.debug('prompted ' + promptedMap);

    Logger.debug(
        'Apex:computeMasteryStats() correctMap=' +
        correctMap +
        ' nonResponsiveMap=' +
        nonResponsiveMap +
        ' incorrectMap=' +
        incorrectMap +
        ' promptedMap=' +
        promptedMap
      )
      .setRecordId(sessions[0])
      .addTag('LFLInvocableSessionStatistics.computeMasteryStats()')
      .addTag('logit()');

    Logger.saveLog();

    Integer temp;
    Integer count = 0;

    for (Id pId : programSet) {
      count = 0;

      /** Dont skip **/
      Mastery_Statistics__c masteryStat = new Mastery_Statistics__c();
      masteryStat.session__c = session;
      masteryStat.previous_status__c = 'ACQ';
      masteryStat.program__c = pId;
      masteryStat.client__c = clientId;

      temp = correctMap.get(pId);
      if (temp != null) {
        masteryStat.totalacquiredcorrect__c = temp;
      } else {
        masteryStat.totalacquiredcorrect__c = 0;
      }
      totalCorrect += (Integer) masteryStat.totalacquiredcorrect__c;
      System.debug(totalCorrect);

      temp = nonResponsiveMap.get(pId);
      if (temp != null) {
        masteryStat.totalacquirednonresponsive__c = temp;
      } else {
        masteryStat.totalacquirednonresponsive__c = 0;
      }
      totalNonResponsive += (Integer) masteryStat.totalacquirednonresponsive__c;
      System.debug(totalNonResponsive);

      temp = incorrectMap.get(pId);
      if (temp != null) {
        masteryStat.totalacquiredincorrect__c = temp;
      } else {
        masteryStat.totalacquiredincorrect__c = 0;
      }
      totalIncorrect += (Integer) masteryStat.totalacquiredincorrect__c;
      System.debug(totalIncorrect);

      temp = promptedMap.get(pId);
      if (temp != null) {
        masteryStat.totalacquiredprompted__c = temp;
      } else {
        masteryStat.totalacquiredprompted__c = 0;
      }
      totalPrompted += (Integer) masteryStat.totalacquiredprompted__c;
      System.debug(totalPrompted);
      insert masteryStat;
    }
    String current = System.now().format();
    //Integer noOfObjectives = programSet.size();
    Decimal percentage = ((totalCorrect +
      totalIncorrect +
      totalNonResponsive +
      totalPrompted) > 0)
      ? (Decimal) (totalCorrect *
        100 /
        (totalCorrect +
        totalNonResponsive +
        totalIncorrect +
        totalPrompted))
      : 0;

    response.outputString =
      '\n---------------------------------------------------------------' +
      '\nSuccessfully generated mastery statistics at ' +
      current +
      '\n---------------------------------------------------------------' +
      '\nCorrect: ' +
      totalCorrect +
      '\nNonResponsive: ' +
      totalNonResponsive +
      '\nIncorrect: ' +
      totalIncorrect +
      '\nPrompted: ' +
      totalPrompted +
      '\n----------------------' +
      '\nPercent Correct: ' +
      percentage +
      '%' +
      '\n----------------------\n';
    responseList.add(response);
    return responseList;
  }

  public class Response {
    @InvocableVariable(
      label='Output'
      description='Calculate Statistics Result'
      required=true
    )
    public String outputString;
  }
}